services:
  mysql:
    image: mysql:8.4
    container_name: cinebook-mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: endsem@db26
      MYSQL_DATABASE: cinebook
    ports:
      - "3307:3306"
    volumes:
      - cinebook_mysql_data:/var/lib/mysql

volumes:
  cinebook_mysql_data:
